import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
	brand: "#2fb314",
	brandStrong: "#18770a",
	brandDeep: "#0d4f2e",
	foreground: "#123129",
	muted: "#5e716b",
	surface: "#ffffff",
	surfaceStrong: "#eef7ea",
	border: "#123129",
	borderSoft: "#d8e8d8",
	background: "#ffffff",
};

export const styles = StyleSheet.create({
	page: {
		padding: 30,
		backgroundColor: COLORS.background,
		fontFamily: "Helvetica",
		fontSize: 10,
		color: COLORS.foreground,
	},
	header: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 20,
	},
	headerLeft: {
		flex: 1,
	},
	headerRight: {
		flex: 1,
		textAlign: "right",
	},
	logo: {
		width: 100,
		height: 40,
		marginBottom: 8,
		objectFit: "contain",
	},
	companyName: {
		fontSize: 24,
		fontWeight: "bold",
		color: COLORS.foreground,
		marginBottom: 4,
	},
	companySlogan: {
		fontSize: 10,
		fontStyle: "italic",
		color: COLORS.muted,
		marginBottom: 12,
	},
	companyInfo: {
		fontSize: 9,
		color: COLORS.muted,
		lineHeight: 1.4,
	},
	quotationTitle: {
		fontSize: 32,
		fontWeight: "bold",
		fontStyle: "italic",
		color: COLORS.foreground,
		marginBottom: 8,
	},
	metaInfo: {
		fontSize: 10,
		color: COLORS.foreground,
		lineHeight: 1.6,
	},
	clientSection: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginBottom: 12,
		paddingBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: COLORS.borderSoft,
		borderBottomStyle: "solid",
	},
	clientLeft: {
		flex: 1,
	},
	clientRight: {
		flex: 1,
		textAlign: "right",
	},
	sectionTitle: {
		fontSize: 11,
		fontWeight: "bold",
		color: COLORS.foreground,
		marginBottom: 8,
	},
	clientInfo: {
		fontSize: 10,
		color: COLORS.foreground,
		lineHeight: 1.5,
	},
	notesSection: {
		marginBottom: 12,
		padding: 10,
		backgroundColor: COLORS.surfaceStrong,
		borderRadius: 4,
	},
	notesText: {
		fontSize: 10,
		color: COLORS.foreground,
		lineHeight: 1.5,
	},
	commercialTable: {
		marginBottom: 12,
	},
	commercialTableHeader: {
		flexDirection: "row",
		backgroundColor: COLORS.brandDeep,
		paddingVertical: 8,
		paddingHorizontal: 6,
	},
	commercialTableHeaderText: {
		color: COLORS.background,
		fontSize: 8,
		fontWeight: "bold",
		textAlign: "center",
	},
	commercialTableRow: {
		flexDirection: "row",
		paddingVertical: 8,
		paddingHorizontal: 6,
		borderBottomWidth: 1,
		borderBottomColor: COLORS.borderSoft,
		borderBottomStyle: "solid",
	},
	commercialTableCell: {
		fontSize: 9,
		color: COLORS.foreground,
		textAlign: "center",
	},
	productsTable: {
		marginBottom: 12,
	},
	productsTableHeader: {
		flexDirection: "row",
		backgroundColor: COLORS.surfaceStrong,
		paddingVertical: 10,
		paddingHorizontal: 8,
		borderWidth: 1,
		borderColor: COLORS.border,
		borderStyle: "solid",
	},
	productsTableHeaderText: {
		fontSize: 9,
		fontWeight: "bold",
		color: COLORS.foreground,
		textAlign: "center",
	},
	productsTableRow: {
		flexDirection: "row",
		paddingVertical: 10,
		paddingHorizontal: 8,
		borderLeftWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderColor: COLORS.border,
		borderStyle: "solid",
	},
	productsTableCell: {
		fontSize: 9,
		color: COLORS.foreground,
	},
	sectionRow: {
		flexDirection: "row",
		paddingVertical: 10,
		paddingHorizontal: 8,
		backgroundColor: COLORS.surfaceStrong,
		borderLeftWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderColor: COLORS.border,
		borderStyle: "solid",
	},
	sectionCell: {
		fontSize: 9,
		fontWeight: "bold",
		color: COLORS.brandDeep,
		textTransform: "uppercase",
	},
	noteRow: {
		flexDirection: "row",
		paddingVertical: 8,
		paddingHorizontal: 8,
		backgroundColor: "#fff8e1",
		borderLeftWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderColor: COLORS.border,
		borderStyle: "solid",
	},
	noteCell: {
		fontSize: 9,
		fontStyle: "italic",
		color: COLORS.muted,
	},
	totalsSection: {
		flexDirection: "row",
		justifyContent: "flex-end",
		marginBottom: 10,
	},
	totalsTable: {
		width: "40%",
	},
	totalsRowLast: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderWidth: 1,
		borderColor: COLORS.border,
		borderStyle: "solid",
		backgroundColor: COLORS.surfaceStrong,
	},
	totalsLabel: {
		fontSize: 10,
		fontWeight: "bold",
		color: COLORS.foreground,
	},
	totalsValueBold: {
		fontSize: 11,
		fontWeight: "bold",
		color: COLORS.foreground,
		textAlign: "right",
	},
	footer: {
		marginTop: 15,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: COLORS.borderSoft,
		borderTopStyle: "solid",
		textAlign: "center",
	},
	footerText: {
		fontSize: 9,
		color: COLORS.muted,
		lineHeight: 1.5,
		marginBottom: 8,
	},
	footerThanks: {
		fontSize: 12,
		fontWeight: "bold",
		color: COLORS.brand,
		textTransform: "uppercase",
	},
});
